#!/usr/bin/env bash
# =============================================================================
# Get AWS Credentials (Wrapper for assume-deploy-role.sh)
# =============================================================================
#
# This wrapper script clears stale AWS session tokens and obtains fresh
# temporary credentials with MFA. The credentials are exported to the current
# shell AND saved to /tmp/aws-session-creds.sh for use by other shells/agents.
#
# Usage:
#   source tools/get-aws-creds.sh
#   # Enter MFA token when prompted
#
# IMPORTANT: Must be sourced (not executed) so env vars propagate.
#
# =============================================================================

# NOTE: We don't use 'set -euo pipefail' because this script is intended to be
# sourced, and setting those options would affect the caller's shell environment.

# ─── Colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No color

# ─── Clear stale AWS session tokens ──────────────────────────────────────────
# Stale/expired AWS_SESSION_TOKEN env vars override ~/.aws/credentials and
# cause "ExpiredToken" or "No MFA device configured" errors. Always unset first.
echo -e "${YELLOW}Clearing any stale AWS session tokens...${NC}"
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

# ─── Get fresh credentials ────────────────────────────────────────────────────
echo -e "${YELLOW}Obtaining fresh credentials with MFA...${NC}"
echo ""

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/assume-deploy-role.sh" "$@"

# Check if assume-role succeeded (AWS_SESSION_TOKEN should be set)
if [[ -z "${AWS_SESSION_TOKEN:-}" ]]; then
  echo -e "${RED}ERROR: Failed to obtain credentials${NC}" >&2
  # shellcheck disable=SC2317
  return 1 2>/dev/null || exit 1
fi

# ─── Save credentials for other shells/agents ─────────────────────────────────
# Security considerations for /tmp storage:
#   - File permissions set to 600 (owner-only read/write)
#   - Credentials are time-limited and expire automatically (1-12 hours)
#   - /tmp is cleared on system reboot
#   - On shared/multi-user systems, consider a more restrictive location
#     (e.g., ~/.aws/tmp-creds.sh with strict umask)
CREDS_FILE="/tmp/aws-session-creds.sh"
cat > "$CREDS_FILE" <<EOF
# AWS temporary credentials — auto-generated by tools/get-aws-creds.sh
# Source this file to use the same session in other shells/agents:
#   source /tmp/aws-session-creds.sh

export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
export AWS_SESSION_TOKEN="${AWS_SESSION_TOKEN}"

# Credentials expire at: $(date -d "+${1:-43200} seconds" -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

chmod 600 "$CREDS_FILE"  # Readable only by current user

# ─── Success message ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✓ Credentials saved to: ${CREDS_FILE}${NC}"
echo ""
echo "Other shells/agents can use these credentials:"
echo -e "  ${YELLOW}source ${CREDS_FILE}${NC}"
echo ""
